### ISSUE TITLE
Make things awesome

### ISSUE THREAD

**Issue by cookiengineer** [Hackmind-ai/Deep-Depth#1]

**Comment by frogg** [comment]
Fixed in bb20f5d06ebbac6883d64f77d052de5fd7679dc6

**Comment by cookiengineer** [comment]
unit test regression in @f795c33002d6c1149d4ca76a2dd6a45a389ec1d9

**Comment by frogg** [comment]
This has been fixed in:
https://github.com/Hackmind-ai/deep-darth

**Comment by cookiengineer** [comment]
Also, our Marketing Team should make use of the preliminary landing page hosted at gh-pages:

https://hackmind-ai.github.io/deep-darth/index.html
